Sources/Pageboy/PageboyScrollDetection.swift
Fix issue where scrolling aggressively and causing post-boundary deceleration would cause an incorrect currentIndex temporarily
=> Fix issue with aggressive scroll deceleration

Sources/Pageboy/PageboyScrollDetection.swift, Sources/Pageboy/PageboyViewController.swift, Sources/PageboyTests/PageboyTransitionTests.swift
- Add bounces property to PageboyViewController.
- Add updateContentOffsetForBounceIfNeeded function to update contentOffset for bounces preference.
Resolves #19
=> Add bounces property for disabling over-scroll bouncing.

Sources/Pageboy/PageboyViewController.swift
I've renamed following.
`PageIndex.atIndex(index: Int)` -> `PageIndex.at(index: Int)`
Then you can initialize it as follows.
```
.at(index: 3)
```
What do yo think?
=> Rename Index.atIndex -> Index.at

Sources/Pageboy/PageboyViewController.swift
There were a couple of issues when using `scrollToPage` on a pager that had `isInfiniteScrollEnabled` set to `true`.
- `.next` used the wrong direction when animating from the last page to the first.
- `.previous` did not work at all when trying to scroll from the first page to the last.
=> Fix infinite scrolling issues.

Sources/Pageboy/PageboyViewController.swift
By providing default implementations in an extension, classes that adopt `PageboyViewControllerDelegate` can implement just the methods they're interested in. (This is equivalent to marking the method `@optional` in Objective-C)
=> Make PageboyViewControllerDelegate functions optional

Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
I used it as child view contoller.
I faced an issue when my pager `scrollView` had `.zero` frame (maybe it happens before applying constrains), not sure exactly how. 
When it is `.zero`, position becomes `NaN` and then it tries to assign to constraint value which is causing a crash.
At the end I'm getting it fine without any constraint warnings.
This is not changing any logic, just preventing a crash if there is some bad value in `position`
=> fix nan position

Sources/Pageboy/Utilities/LocalizationUtils.swift
- Fix missing fallback for devices running iOS lower than `9.0` that were unable to use `userInterfaceLayoutDirection(for:)`.
=> Add Right-to-Left interface layout support when using iOS 8

Example/Pageboy-Example/TransparentNavigationBar.swift, Sources/Pageboy/Extensions/PageboyViewController+Transitioning.swift, Sources/Pageboy/PageboyViewController.swift, Sources/Pageboy/Utilities/TransitionOperation.swift
Hi Dear
@msaps I found the leaking object which holds `pageboyViewController` and doesn't allow to deallocate `pageboyViewController` after pop or dismiss
- Fixed strong reference in CADisplayLink
- Clear viewControllers content after deallocated 
- Fixed animation property strong reference
issue reference : [MemoryLeak](https://github.com/uias/Pageboy/issues/83)
=> Fixed Memory leaking issue #83

Sources/Pageboy/Extensions/PageboyViewController+Management.swift
When In-Call StatusBar Mode, UIPageViewController will have Top-margin.
I've moved pinToSuperviewEdges after addSubview.
But, pinToSuperviewEdges always guard-return in existing code.
Do you have any reasons for it?
I've attached screenshots below.
What do you think?
Before
ViewTree has double top-margin.
After
ViewTree has single top-margin.
=> Set constraints after addSubview for In-Call StatusBar mode

Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
Add guard functions to ensure public facing delegates are checking components for use. Resolves #98
=> Add guards to public facing delegates.

README.md
I believe there was an error in the cocoapods instructions - I copied and pasted the installation line (`pod 'Pageboy' ~> 2.0`) and got a syntax error. I've changed it to `pod 'Pageboy', '~> 2.0'`
=> Update cocoapods instructions in README

Sources/Pageboy/PageboyViewController.swift
Improve the logic that handles decided whether to proceed with an animated scroll operation while another scroll operation could be occurring.
Improvements to help resolve #109
=> Improve blocking logic for animated scrolling operations

Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift, Sources/Pageboy/PageboyViewController.swift
Issue Replication:
1. Begin to page to a new index but then stop the gesture early so that the pager stays on the current index
2. Present and dismiss a view controller over the pager
3. The pager will now be at the index that you had started to move to, but not the index that you ended at.
Cause:
expectedTransitionIndex on PageboyViewController is set when the user begins the paging gesture, however, the expectedTransitionIndex is never cleared and the currentIndex is never updated if the user cancels the gesture.  Therefore, when scrollToPage is triggered on viewWillAppear, the expectedTransitionIndex does not match the currentIndex and therefore the pager switches pages even though that is not the intention of the user.
Fix:
expectedTransitionIndex is set to nil at the end of the …
=> Fixed incorrect scrolling to index on pager appearance

Sources/Pageboy/PageboyViewController+Management.swift, Sources/Pageboy/PageboyViewController+Updating.swift, Sources/Pageboy/PageboyViewController.swift, Sources/Pageboy/Transitioning/PageboyViewController+Transitioning.swift, Sources/Pageboy/Transitioning/TransitionOperation.swift, Sources/Pageboy/Utilities/Extensions/UIView+AutoLayout.swift, Sources/Pageboy/Utilities/Extensions/UIView+Localization.swift
Decided to take a crack at fixing #153 and ended up poking around a bit more than I planned. Key points for this PR:
- Move all FatalErrors to #DEBUG only, as it should not be done in release/prod code. Hard crashing like this will, AFAIK, break people's crash reporting/make crashes seem random.
- let self=self aliasing is a compiler bug and will be removed in future swift versions, might as well fix now and use a guard inside weak self closures for cleaning up optional chaining.
- Main thread safety: More enforcement of main thread usage for functions that manipulate UIKit classes. Conversion involved adding asserts, making current functions private and adding a public function that thread casts the private function to main.
- Closure Captures: Generally closures should capture their …
=> Thread Safety, closure captures, debug-only FatalErrors, self-self aliasing, misc tweaks

Sources/Pageboy/Utilities/Extensions/DispatchQueue+main.swift
=> execute task in main thread synchronously

Example/Pageboy-Example.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
>Xcode 9.3 adds a new IDEWorkspaceChecks.plist file to a workspace's shared data, to store the state of necessary workspace checks. Committing this file to source control will prevent unnecessary rerunning of those checks for each user opening the workspace. (37293167)
https://developer.apple.com/library/archive/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html
=> Xcode 9.3+ recommended versioning of IDEWorkspaceChecks.plist

Sources/Pageboy/Model/NavigationDirection.swift, Sources/Pageboy/Model/Page.swift, Sources/Pageboy/PageboyViewController+Management.swift, Sources/Pageboy/PageboyViewController+Updating.swift, Sources/Pageboy/PageboyViewController.swift, Sources/Pageboy/Transitioning/PageboyViewController+Transitioning.swift, Sources/Pageboy/UIViewController+Pageboy.swift
Quite annoying to have all those Xcode warnings when using PageBoy.
=> 'public' modifier is redundant for * declared in a public extension

Sources/Pageboy.xcodeproj/project.pbxproj, Sources/Pageboy/PageboyViewController.swift, Sources/Pageboy/Utilities/IndexedObjectMap.swift, Sources/Pageboy/Utilities/ObjectIndexMap.swift, Sources/Pageboy/Utilities/WeakContainer.swift
Fix for #198 caused issues with invalid keys in map. Changed so that the map is keyed by page indexes rather than the object (view controller)
=> Fix issue where index map could have invalid keys

Sources/Pageboy/UIViewController+Pageboy.swift
This commit fixes an Xcode 10.2 warning.
=> deprecated value can only be used for iOS or tvOS version

Sources/Pageboy/PageboyViewController+ScrollCalculations.swift, Sources/Pageboy/PageboyViewController.swift, Sources/Pageboy/Transitioning/PageboyViewController+Transitioning.swift, Sources/Pageboy/Transitioning/TransitionOperation+Action.swift
navigationOrientation is an Objective-C enum, so it's easy to pass an arbitrary integer value and there is an Xcode warning for that.
This pull request does:
- document and assert that only .horizontal and .vertical can be used for `navigationOrientation`
- solves the Xcode warnings by adding `@unknown default:`
- declare `let navigationOrientation = self.navigationOrientation` to avoid multiple accesses to the same getter (and potential threading issues)
=> Documenting that only .horizontal and .vertical are supported. (solves an Xcode warning for additional unknown values)

Sources/Pageboy/PageboyViewController+Management.swift, Sources/Pageboy/PageboyViewController.swift
Also fixes another SwiftLint warning, the one for `empty_count` (I know you've disabled it, but it's still better practice to use `isEmpty`).
=> SwiftLint warning: Adding weak to a computed property has no effect.

Sources/Pageboy/PageboyViewController.swift
We needed to change the minimumNumberOfTouches for the panning gesture recognizer of the original UIPageViewController:
* Adds public getter for UIPageViewController
* Adds getter / setter for numberOfTouches for the underlying pageViewController
This allows the quick and easy change of the required numberOfTouches for swiping a page.
=> Adds getter UIPageViewController

Example/Pageboy-Example/PageViewController.swift, Sources/Pageboy/PageboyViewController+ScrollDetection.swift, Sources/Pageboy/Protocols/PageboyViewControllerDelegate.swift
I added a new call to the Pageboy delegate: It handles aborted scrolling attempts. If there's need for a default implementation for this delegate (so this change doesn't brake any existing implementation) I could add this as well.
Motivation: As already discussed in #181 we need to know if a page transition was aborted or completed. Took as nearly one (1) year 🙄
=> Adds abortScrollToPage delegate

Package.swift
This prevents the mixed language error when adding the package via SwiftPM.
=> Excludes header file from sources

Sources/Pageboy.xcodeproj/project.pbxproj, Sources/Pageboy/PageboyViewController+Updating.swift, Sources/Pageboy/PageboyViewController.swift, Sources/Pageboy/Utilities/Extensions/UIScrollView+Interaction.swift
Fixes a number of issues that were related to the dynamic insertion/deletion logic in `PageboyViewController`.
Specifically:
- Fixes issue where inserting a page at the current index with `doNothing` `PageUpdateBehavior` would display the inserted view controller (Resolves #211)
- Fix issue where deleting a page on an upper index could cause index corruption.
- Fix issue where scroll interaction during updates could cause index corruption (touches are now forcibly cancelled and interaction disabled until updates have completed).
=> Fix issues with dynamic insertion + removal

Sources/Pageboy/PageboyViewController+Management.swift
If viewController is only one and infinite scroll, there was a situation that the view was not visible.
=> Fix infinite scroll bug

CHANGELOG.md, Sources/Pageboy/Utilities/PatchedPageViewController.swift
=> Fix crash within `UIPageViewController` during fast sequential page transitions

Sources/Pageboy/Utilities/PatchedPageViewController.swift
@msaps The check for isAnimated should be on both levels of `super.setViewControllers(...)` to prevent the crash from [this issue](https://github.com/uias/Pageboy/issues/277 )
=> also add check isAnimating on first setViewControllers()
