uias/Pageboy

- Sources/Pageboy/PageboyViewController.swift
- Fix issue where PageboyViewController incorrectly observes scroll updates during orientation chages.
> Fix issues with orientation updates

- Sources/Pageboy/PageboyViewController.swift
> Fix retain issues with delegate & dataSource

- Example/Pageboy-Example/PageViewController.swift
- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/PageboyAutoScroller.swift
- Sources/Pageboy/PageboyScrollDetection.swift
- Sources/Pageboy/PageboyViewController.swift
- Sources/PageboyTests/PageboyAutoScrollTests.swift
- Sources/PageboyTests/PageboyDataSourceTests.swift
Add `PageboyAutoScroller` class and `autoScroller` property to `PageboyViewController`, to allow for automatic time-based page scroll transitions. Resolved #3
> Add AutoScroller

- Sources/Pageboy/PageboyAutoScroller.swift
- Sources/PageboyTests/PageboyAutoScrollTests.swift
- Update `isEnabled` to be public in `PageboyAutoScroller`
> Add additional auto scroller tests

- README.md
- Adding Carthage installation to Readme
- Adding 3 new badges on top of Readme (Swift 3.0, Carthage Compatible ,Github Releases)
> Updating README file 

- Sources/Pageboy/PageboyAutoScroller.swift
Fix retain cycle issue with PageboyAutoScroller handler. Resolves #34
> Fix memory issue in PageboyAutoScroller

- Sources/Pageboy/PageboyViewController.swift
correct me if I'm wrong but there is missing `addChildViewController` method
> add page view controller on stack of child views

- Sources/Pageboy/PageboyViewController.swift
> Move page view controller setup to viewDidLoad

- Sources/Pageboy/PageboyScrollDetection.swift
- Sources/Pageboy/PageboyViewController.swift
- Update to use isTracking instead of isDragging for scroll position detection
> Add isTracking property

- .travis.yml
- fastlane/Appfile
- fastlane/Fastfile
> Add support for Fastlane releases

- Sources/Pageboy/PageboyViewController.swift
> Add delaysContentTouches property

- Sources/Pageboy/Extensions/PageboyViewController+Management.swift
- Sources/Pageboy/Extensions/PageboyViewController+Transitioning.swift
- Sources/Pageboy/PageboyViewController.swift
- Improve internal UIPageViewController lifecycle to allow for optional existance
> Improve internal lifecycle management

- Example/Pageboy-Example/PageViewController.swift
- Sources/Pageboy/Utilities/TransitionOperation+Action.swift
> Fix issues with vertical orientation

- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
- Sources/Pageboy/Extensions/PageboyViewController+Transitioning.swift
- Sources/Pageboy/PageboyViewController.swift
- Sources/Pageboy/Utilities/LocalizationUtils.swift
- Sources/Pageboy/Utilities/TransitionOperation+Action.swift
> Add support for Right-To-Left language localization

- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/Extensions/UIViewController+PageboyExtras.swift
- Add UIViewController extension with `parentPageboyViewController` property. #72
> Add accessor for PageboyViewController to child VC's

- Pageboy.podspec
- README.md
- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/Utilities/LocalizationUtils.swift
Hi Dear
I made your library to support ios 8 and later, also checked on devices on 8.1 and 8.4.1 and 10.3.2
> iOS 8 and later 

- Sources/Pageboy/Extensions/PageboyViewController+Transitioning.swift
- Fix issue where animated transitions with greater than index ranges of 1 would not provide positional updates correctly.
> Fix issue with transition updates

- Sources/Pageboy/PageboyViewController.swift
#109 
Referenced from lucoceano/Pager#17
> Attempt to fix crashing on intense scroll action

- Example/Pageboy-Example/ChildViewController.swift
- Example/Pageboy-Example/PageViewController+Appearance.swift
- Sources/Pageboy/Extensions/PageboyViewController+Management.swift
On initial page load.
Resolves #114
> Fix issues with custom status bar style

- Example/Pageboy-Example.xcodeproj/project.pbxproj
- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/Extensions/PageboyViewController+Management.swift
- Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
- Sources/Pageboy/PageboyViewController.swift
> Add improved guarding to avoid scroll overlap crashes

- Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
- Sources/Pageboy/Extensions/PageboyViewController+Transitioning.swift
- Sources/Pageboy/PageboyViewController.swift
Add `showsPageControl` to allow for displaying the native `UIPageViewController` page control. #116
> Add support for built in UIPageControl

- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/Utilities/UIApplication+SafeShared.swift
- Sources/Pageboy/Utilities/ViewUtilities/UIView+Localization.swift
> Add safeShared UIApplication extension

- Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
> Fix scroll detection edge case when decelerating on page index

- Sources/Pageboy/Extensions/PageboyViewController+ScrollDetection.swift
> Fix incorrect current index when scrolling infinitely

- Sources/Pageboy/Extensions/PageboyViewController+Management.swift
- Sources/Pageboy/Extensions/PageboyViewController+NavigationDirection.swift
- Sources/Pageboy/Extensions/PageboyViewController+Transitioning.swift
> Fix animated transition issues when using RtL languages

- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/PageboyViewController+Management.swift
- Sources/Pageboy/PageboyViewController.swift
- Sources/Pageboy/Transitioning/PageboyViewController+Transitioning.swift
- Sources/Pageboy/Utilities/Extensions/DispatchQueue+main.swift
- Sources/Pageboy/Utilities/Extensions/UIView+Localization.swift
- Add convenient extension for executing code in main thread only if necessary.
- Remove unnecessary assert.
> add DispatchQueue+main

- Example/Pageboy-Example/PageViewController.swift
- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy/PageboyViewController+Management.swift
- Sources/Pageboy/PageboyViewController+ScrollDetection.swift
- Sources/Pageboy/PageboyViewController.swift
- Sources/Pageboy/Utilities/ObjectIndexMap.swift
- Sources/Pageboy/Utilities/WeakContainer.swift
Update viewController index map to use weak referenced view controllers, as before it would strongly retain any view controller that was displayed in the `PageboyViewController`.
#198
> Fix view controller memory issues

- Cartfile.private
- Cartfile.resolved
- Example/Pageboy-Example.xcodeproj/project.pbxproj
- Example/Pageboy-Example/ChildViewController.swift
- Example/Pageboy-Example/GradientView.swift
- Example/Pageboy-Example/GradientViewController.swift
- Example/Pageboy-Example/UINavigationController+Utilities.swift
- Sources/.swiftlint.yml
- Sources/Pageboy.xcodeproj/project.pbxproj
- Sources/Pageboy.xcodeproj/xcshareddata/xcschemes/Pageboy iOS.xcscheme
- Sources/Pageboy.xcodeproj/xcshareddata/xcschemes/Pageboy tvOS.xcscheme
- Sources/Pageboy/PageboyViewController+Management.swift
- Sources/Pageboy/PageboyViewController.swift
- Sources/Pageboy/UIViewController+Pageboy.swift
Xcode 10.2,  Swift 5 and improved Swift 4 support
> Add Swift 5 compatibility

- Pageboy.podspec
> Fix Swift version in podspec

- Example/Pageboy-Example/PageViewController.swift
- Sources/Pageboy/PageboyViewController+Updating.swift
- Sources/Pageboy/PageboyViewController.swift
- Fix issue where a page could not be inserted when no other pages exist #209 
- Fix issue where the last page could not be deleted #208
> Fix issues with deletion and insertion of pages.

- Package.swift
- Pageboy.xcworkspace/contents.xcworkspacedata
- Adds support for Swift Package usage in Xcode 11
uias/Tabman#453
> Add Xcode 11 Swift Package support

- Sources/Pageboy/PageboyViewController+Management.swift
- Sources/Pageboy/Patches/PatchedPageViewController.swift
Good library! 
However, [this](https://stackoverflow.com/q/12939280/715593) problem still happens even with Pageboy. So, I wrapped [this](https://stackoverflow.com/a/13253884/715593) solution into a subclass and created a PR.
> fix not updating dataSource on setViewControllers animated

- CHANGELOG.md
Copy & Paste error for 3.7.x changelog
> Fix Changelog 3.7.x releases

- Sources/Pageboy/PageboyViewController+Management.swift
- Sources/Pageboy/PageboyViewController.swift
Hi,
I propose making the isDirectionalLockEnabled property of scrollView in PageboyViewController configurable.
cf. https://developer.apple.com/documentation/uikit/uiscrollview/1619390-isdirectionallockenabled
I hope you will consider it.
Thank you for your great library!
> Add isDirectionalLockEnabled property

- Sources/Pageboy/PageboyViewController.swift
Added delete callback as I had the problem with removal taking effect as well.
[Related issue](https://github.com/uias/Pageboy/issues/289)
> Added: delete callback
